name: Test Pizza Johnny
favicon: null
layout_spectrum: 0.59597
typography_spectrum: 0.1315789
title: Test Pizza Johnny
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#CB2D2F'
    - '#FFFFFF'
    - '#22A563'
    - '#661718'
  brandStrength: 0.625
  lightness: 0.6662107
  saturation: 0.5633727
  rhythmicContrast: 0.8437164
purpose: []
